### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by Shiba-Kar** [appwrite/sdk-for-flutter#105]
### 👟 Reproduction steps

1. Write to USER database and write to username collection 
 ```dart 
    
 static Future<bool> saveUsername(
    Databases databases,
    String username,
    String userId,
  ) async {
    try {
      await databases.createDocument(
        databaseId: userDatabaseID,
        collectionId: usernameCollectionID,
        documentId: userId,
        permissions: [
          Permission.write(Role.user(userId)),
          Permission.update(Role.user(userId)),
          Permission.delete(Role.user(userId)),
          Permission.read(Role.any())
        ],
        data: {"username": username},
      );
      return true;
    } on AppwriteException catch (e) {
      Utils.debLog(e);
      return false;
    }
  }

  ```
2. Read the list of usernames in the usernames collection 

```dart
  static Future<bool> checkUsername(
    Databases databases,
    String username,
  ) async {
    var documentList = await databases.listDocuments(
      databaseId: userDatabaseID,
      collectionId: usernameCollectionID,
      queries: [Query.equal('username', username)],
    );
    return true;
}
```

### 👍 Expected behavior

List of Documets

### 👎 Actual Behavior

Error

```shell
Reloaded 1 of 1787 libraries in 1,813ms (compile: 46 ms, reload: 741 ms, reassemble: 845 ms).
E/flutter (15782): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>'
E/flutter (15782): #0      new Document.fromMap
package:appwrite/…/models/document.dart:41
E/flutter (15782): #1      new DocumentList.fromMap.<anonymous closure>
package:appwrite/…/models/document_list.dart:20
E/flutter (15782): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
E/flutter (15782): #3      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
E/flutter (15782): #4      new List.from (dart:core-patch/array_patch.dart:41:17)
E/flutter (15782): #5      new DocumentList.fromMap
package:appwrite/…/models/document_list.dart:20
E/flutter (15782): #6      Databases.listDocuments
package:appwrite/services/databases.dart:35
```

### 🎲 Appwrite version

Version 2.0.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Shiba-Kar** [comment]
No Exceptions on the model if there is no permissions in the json.
