### ISSUE TITLE
Unhandled Exception: type 'String' is not a subtype of type 'int' of 'index'

### ISSUE THREAD

**Issue by patricktslee** [appwrite/sdk-for-flutter#18]
I have question on my flutter App to login Appwrite.  I tried to server down the Appwrite and login the system.  It is supposed to exception and print the error message.  However it didn’t work on my below code and get the below error log

Login code

```
Future login({String email, String password}) async {
    try {
      await account.createSession(email: email, password: password);
      return true;
    } on AppwriteException catch (e) {
      print('ApiService login error ' + e.message);
      return false;
    }
  }

```
**Error log**

```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: type 'String' is not a subtype of type 'int' of 'index'


#0      Client.call      package:appwrite/client.dart:153
<asynchronous suspension>
#1      ApiService.login     package:praise/…/data/ApiService.dart:28
<asynchronous suspension>
#2      HomeRepository.login.<anonymous closure> (package:praise/pages/home/data/home_repository.dart)        package:praise/…/data/home_repository.dart:1
<asynchronous suspension>
```

I use appwrite: 0.5.0-dev.1

**Comment by lohanidamodar** [comment]
@patricktslee Thank you for your support and issue. We have already merged the PR that resolves this issue
https://github.com/appwrite/sdk-generator/pull/164
