### ISSUE TITLE
🐛 Bug Report: Switching to any authenticator app while creating a Google OAuth Session breaks the login flow

### ISSUE THREAD

**Issue by metalwings** [appwrite/sdk-for-flutter#181]
## Requirements
- Google Account with an activated 2FA (two-factor-authentication) option
- An android device which is logged into the same google account
- appwrite project with Google OAuth setup

## Reproduction
1. Login into your google account through `createOAuth2Session(provider: "google")`
2. You switch to your 2FA application
3. After confirming your 2FA, the login window is automatically closed but you're not logged in

## Further information
I've created a minimal reproduction repository: 
https://gitlab.com/metalwings/appwrite-flutter-oauth2-demo

In my case the default "is this you?" screen is automatically shown by android as soon as I try to login into my account.

<img src="https://github.com/appwrite/sdk-for-flutter/assets/6256062/da8dfb5e-a94b-4ec9-9315-2b3ff8c63561" width="120" height="300">

### 👍 Expected behavior

Switching to any authenticator app doesn't break the login flow. I should be able to close the app, check my 2FA Code (or press "that's me") and be able to login

### 👎 Actual Behavior

The login flow is cancelled due to loss of app focus.
An exception is thrown:
```
E/flutter ( 6554): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(CANCELED, User canceled login, null, null)
E/flutter ( 6554): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter ( 6554): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter ( 6554): <asynchronous suspension>
E/flutter ( 6554): #2      FlutterWebAuth2MethodChannel.authenticate 
(package:flutter_web_auth_2_platform_interface/method_channel/method_channel_flutter_web_auth_2.dart:16:7)
```

### 🎲 Appwrite version

Version 2.0.x

### 💻 Operating system

Linux

### 🧱 Your Environment

No. Problem can be reproduced in the appwrite cloud version 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by metalwings** [comment]
Playing around with the `android:launchMode` in https://gitlab.com/metalwings/appwrite-flutter-oauth2-demo/-/blob/main/android/app/src/main/AndroidManifest.xml?ref_type=heads#L9 as suggest by @stnguyen90 didn't help.

**Comment by metalwings** [comment]
Tested on iOS.
Everything works there, because the sign-in window behavior is different.

Also found a new clue: For some reason, the browser window "Sign in with Google" is closed automatically as soon as I try to switch to another app.

https://github.com/appwrite/sdk-for-flutter/assets/6256062/97e719c2-1f23-40f0-849d-db91f00a3d2d

**Comment by metalwings** [comment]
### Workaround:
 - Initialize the OAuth Session in a separate WebView / CustomTab (with `url_launcher` for example)
 - After successful login, trigger the AppWrite OAuth Flow

**Comment by Namaneo** [comment]
Hey, I'm also seeing this behavior. I tried your workaround and this opens the authentication view twice (as I would have expected). Indeed the first one does behave better. @metalwings Have you find a better workaround since?

**Comment by Namaneo** [comment]
I actually found the root cause: some deprecated `flutter_web_auth_2` configuration still being used. Opened a PR about it in the `sdk-generator` repository.
