### ISSUE TITLE
🐛 Bug Report: type List<dynamic>' is not a subtype of type 'List<String>

### ISSUE THREAD

**Issue by develocode777** [appwrite/sdk-for-flutter#224]
### 👟 Reproduction steps

When I try this portion of code:

`
    DocumentList listGeneralInfo = await globals.appwriteDB.listDocuments(
      collectionId: Env.appwriteGeneralInfoCollection,
      databaseId: Env.appwriteGeneralInfo,
    );
`

I get the error `List<dynamic>' is not a subtype of type 'List<String>`

### 👍 Expected behavior

There should be no errors.

### 👎 Actual Behavior

I get the error `List<dynamic>' is not a subtype of type 'List<String>`

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

self-hosted 1.6.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by develocode777** [comment]
I downloaded the package locally and modified this portion of the code (session.dart) as someone suggested in discord and now it works:

` factors: map['factors'] ?? [],` to ` factors: map['factors'].cast<String>() ?? <String>[],`

```
  factory Session.fromMap(Map<String, dynamic> map) {
    return Session(
      $id: map['\$id'].toString(),
      $createdAt: map['\$createdAt'].toString(),
      $updatedAt: map['\$updatedAt'].toString(),
      userId: map['userId'].toString(),
      expire: map['expire'].toString(),
      provider: map['provider'].toString(),
      providerUid: map['providerUid'].toString(),
      providerAccessToken: map['providerAccessToken'].toString(),
      providerAccessTokenExpiry: map['providerAccessTokenExpiry'].toString(),
      providerRefreshToken: map['providerRefreshToken'].toString(),
      ip: map['ip'].toString(),
      osCode: map['osCode'].toString(),
      osName: map['osName'].toString(),
      osVersion: map['osVersion'].toString(),
      clientType: map['clientType'].toString(),
      clientCode: map['clientCode'].toString(),
      clientName: map['clientName'].toString(),
      clientVersion: map['clientVersion'].toString(),
      clientEngine: map['clientEngine'].toString(),
      clientEngineVersion: map['clientEngineVersion'].toString(),
      deviceName: map['deviceName'].toString(),
      deviceBrand: map['deviceBrand'].toString(),
      deviceModel: map['deviceModel'].toString(),
      countryCode: map['countryCode'].toString(),
      countryName: map['countryName'].toString(),
      current: map['current'],
      factors: map['factors'].cast<String>() ?? <String>[],
      secret: map['secret'].toString(),
      mfaUpdatedAt: map['mfaUpdatedAt'].toString(),
    );
```

**Comment by nathanael540** [comment]
createExecution show the same error

```
type 'List<dynamic>' is not a subtype of type 'List<String>'
StackTrace: #0      new Execution.fromMap (package:appwrite/src/models/execution.dart:81:42)
#1      Functions.createExecution (package:appwrite/services/functions.dart:68:29)
<asynchronous suspension>
```

**Comment by sabitzhambay** [comment]
you just need to replace final List<String> factors with final List factors; inside the Session class

**Comment by Gajjar-Mohit** [comment]
Facing same error in user.dart and session.dart

`Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'List<String>'
 new Session.fromMap (package:appwrite/src/models/session.dart:152:31)
 Account.createEmailPasswordSession (package:appwrite/services/account.dart:646:27)
 `

`Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'List<String>'
E/flutter (29288): #0      new User.fromMap (package:appwrite/src/models/user.dart:95:29)
E/flutter (29288): #1      Account.create (package:appwrite/services/account.dart:56:24)
`

**Comment by sabitzhambay** [comment]
you just need to replace final List<String> factors with final List factors; inside the Session class

**Comment by sabitzhambay** [comment]
`you just need to replace "final List<String> factors" with final List factors; inside the Session class`

**Comment by stnguyen90** [comment]
This should be fixed in version [13.1.1](https://github.com/appwrite/sdk-for-flutter/releases/tag/13.1.1).
