### ISSUE TITLE
🐛 Bug Report: createFloatAttribute() 'toDouble' was called on null.

### ISSUE THREAD

**Issue by generalxhd** [appwrite/sdk-for-flutter#49]
### 👟 Reproduction steps

Execute the following function:
```
database.createFloatAttribute(
          collectionId: "collection",
          key: "someKey",
          xrequired: true)
```

### 👍 Expected behavior

The function should be executed without an error.

### 👎 Actual Behavior

The function returns:
```
NoSuchMethodError: The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:68:5)
#1      new AttributeFloat.fromMap (package:dart_appwrite/src/models/attribute_float.dart:49:32)
#2      Database.createFloatAttribute (package:dart_appwrite/services/database.dart:279:34)
<asynchronous suspension>
```

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite 0.12

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by wess** [comment]
Let's dive in, shall we?

**Comment by generalxhd** [comment]
Oops sorry, I noticed this is the wrong repository. It should be in the sdk for dart. Should I remove the issue and raise it again in the correct repo?

**Comment by wess** [comment]
> Oops sorry, I noticed this is the wrong repository. It should be in the sdk for dart. Should I remove the issue and raise it again in the correct repo?

Please :)

**Comment by wess** [comment]
Moving to dart
